name: CI/CD Pipeline - Parcial 1

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Instalar dependencias
        run: npm install

      - name: 4. Ejecutar validación de la app
        run: node src/index.js & sleep 2 && kill $!

  deploy-simulation:

    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: 5. Checkout del código
        uses: actions/checkout@v4

      - name: 6. Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 7. Construir contenedor Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: node-mysql-app:latest

      - name: 8. Confirmar Despliegue Exitoso
        run: echo "¡Despliegue simulado con éxito!"